In [70]:
from functions.filtrar_datos_real_vert import filtrar_datos_vertical
from functions.PitotProcess import PitotProcess
from functions.calcVelocity import calcVelocity
import pandas as pd
import numpy as np

El archivo debe tener 52 filas, con "fin" como columna final y 51 sólo de de datos

In [71]:
archivo = "Prueba_recolectada.txt"
dataset_1 = pd.read_csv(archivo, header=None)
dataset_1 = dataset_1.iloc[:, :-1] # Remove last column because is "final"
dataset_1.columns = ['time', 'height', 'bme_temp', 'bme_press', 'bme_hum', 'bmp_temp',
       'bmp_press', 'voc_raw', 'accel_x', 'accel_y', 'accel_z', 'lin_accel_x',
       'lin_accel_y', 'lin_accel_z', 'gyro_x', 'gyro_y', 'gyro_z', 'mag_x',
       'mag_y', 'mag_z', 'euler_x', 'euler_y', 'euler_z', 'quat_w', 'quat_x',
       'quat_y', 'quat_z', 'year', 'month', 'day', 'hour', 'minute', 'second',
       'lon', 'lat', 'alt', 'velN', 'velE', 'velD', 'pump_feedback',
       'valven_feedback', 'valve1_feedback', 'valve2_feedback','a', 'press_1',
       'temp_1','a', 'press_2', 'temp_2', 'a','press_3', 'temp_3','a', 'press_4',
       'temp_4']
print(dataset_1.columns)
print(len(dataset_1.columns))

# QUITAR LAS a

Index(['time', 'height', 'bme_temp', 'bme_press', 'bme_hum', 'bmp_temp',
       'bmp_press', 'voc_raw', 'accel_x', 'accel_y', 'accel_z', 'lin_accel_x',
       'lin_accel_y', 'lin_accel_z', 'gyro_x', 'gyro_y', 'gyro_z', 'mag_x',
       'mag_y', 'mag_z', 'euler_x', 'euler_y', 'euler_z', 'quat_w', 'quat_x',
       'quat_y', 'quat_z', 'year', 'month', 'day', 'hour', 'minute', 'second',
       'lon', 'lat', 'alt', 'velN', 'velE', 'velD', 'pump_feedback',
       'valven_feedback', 'valve1_feedback', 'valve2_feedback', 'a', 'press_1',
       'temp_1', 'a', 'press_2', 'temp_2', 'a', 'press_3', 'temp_3', 'a',
       'press_4', 'temp_4'],
      dtype='object')
55

In [72]:
col_needed = [
    'press_1', 'press_2', 'press_3', 'press_4',
    'temp_1', 'temp_2', 'temp_3', 'temp_4', 'bme_press',
    'euler_x', 'euler_y', 'euler_z',
    'lin_accel_x', 'lin_accel_y', 'lin_accel_z',
    'height'
]
dataset = dataset_1[col_needed] #Crea un nuevo DataFrame con las columnas necesarias
dataset

# press_1 = pitot D, puerto cero
# press_2 = pitot A, puerto uno
# press_3 = pitot B, puerto dos
# press_4 = pitot C, puerto tres
# A y C paralelos, en eje X de IMU
# B y D paralelos, en eje Y de IMU

,press_1,press_2,press_3,press_4,temp_1,temp_2,temp_3,temp_4,bme_press,euler_x,euler_y,euler_z,lin_accel_x,lin_accel_y,lin_accel_z,height
0,-41.56,-40.51,77.33,-34.20,21.83,20.85,20.36,20.76,915.96,0.00,0.00,0.00,0.00,0.00,0.00,860.0
1,-43.66,-33.14,77.33,-34.20,21.83,20.85,20.36,20.76,915.93,358.94,12.25,1.56,0.00,0.07,-0.04,870.0
2,-43.66,-40.51,77.33,-34.20,21.83,20.95,20.36,20.76,915.96,358.94,12.25,1.56,-0.03,0.00,-0.02,880.0
3,-38.40,-40.51,78.39,-34.20,21.93,20.95,20.36,20.76,915.94,358.94,12.38,1.56,0.00,-0.06,-0.01,890.0
4,-38.40,-42.61,82.59,-34.20,21.93,20.95,20.36,20.76,915.94,358.94,12.44,1.56,-0.04,-0.10,-0.10,900.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77,-40.51,-39.46,81.54,-37.35,22.03,21.05,20.56,20.95,915.67,3.44,-13.94,0.25,-0.24,-1.03,-0.10,860.0
78,-41.56,-40.51,81.54,-36.30,22.03,21.05,20.56,20.95,915.69,2.88,-16.56,0.88,-0.12,-0.11,-0.03,850.0
79,-43.66,-39.46,78.39,-37.35,21.93,21.05,20.56,20.95,915.68,0.81,2.69,-0.25,0.01,0.12,-0.05,840.0
80,-43.66,-40.51,82.59,-37.35,22.03,21.05,20.56,20.95,915.68,0.81,-9.31,2.00,0.25,-0.05,0.02,830.0
81,-43.66,-39.46,79.44,-37.35,22.03,21.05,20.56,20.95,915.70,1.12,-7.50,2.88,-0.07,-0.71,0.47,820.0

In [73]:
#dataset = dataset.iloc[:,:8]#se toman solo las 8 columnas de los datos tomados
datatemp = pd.DataFrame(columns=dataset.columns)#datafrae temporal para el datahistory
datatemp = dataset.head(34)#los primeros 34 valores de la medicion se nulifican para definir el filtro
#dataset

In [74]:
database_pitots = pd.DataFrame(columns=["V1", "V2", "V3", "V4", "N", "E", "D"]) #creacion de database para guardar datos de cada pitot

In [75]:
""" local_pressure = 101325 #esto es la presion atmosferica en Pa. Se puso ahí 1 atm
euler_angles = [0,0,0] #angulos de euler dados por IMU anulados por pruebas estaticas
offset_pitots = [0, 0, 0, 0] #Valores de los offset de cada sensor de presión. primero se le resta el offset y luego se filtran los datos
imu_velocity = [0, 0, 0] #velocidad del IMU en m/s

for i in range(len(dataset)):
    local_temp = datatemp[['temp_1', 'temp_2', 'temp_3', 'temp_4' ]].mean().mean()
    new_Value = dataset.loc[i]

    filtered_data, datatemp = filtrar_datos_vertical(new_Value,datatemp, offset_pitots)
    pressures_data = filtered_data[0:4]

    rho = (local_pressure*0.02897)/(8.314472*(local_temp+273.15))
    
    velocity_pitots = list(map(lambda x: ((2*abs(x)/rho)**0.5), pressures_data)) #se calcula la velocidad de cada pitot con la presion filtrada                              
    
    #proccessed_pitot_couples = PitotProcess(pressures_data, rho, euler_angles) #TAL VEZ ELIMINAR LOCAL_TEMP
    wind_velocity_NED = PitotProcess(pressures_data, rho, euler_angles, imu_velocity)

    database_pitots.loc[i] = [velocity_pitots[0], velocity_pitots[1], velocity_pitots[2], velocity_pitots[3], wind_velocity_NED[0], wind_velocity_NED[1], wind_velocity_NED[2]]
    #print(filtered_data-new_Value)

print(rho) """

" local_pressure = 101325 #esto es la presion atmosferica en Pa. Se puso ahí 1 atm\neuler_angles = [0,0,0] #angulos de euler dados por IMU anulados por pruebas estaticas\noffset_pitots = [0, 0, 0, 0] #Valores de los offset de cada sensor de presión. primero se le resta el offset y luego se filtran los datos\nimu_velocity = [0, 0, 0] #velocidad del IMU en m/s\n\nfor i in range(len(dataset)):\n    local_temp = datatemp[['temp_1', 'temp_2', 'temp_3', 'temp_4' ]].mean().mean()\n    new_Value = dataset.loc[i]\n\n    filtered_data, datatemp = filtrar_datos_vertical(new_Value,datatemp, offset_pitots)\n    pressures_data = filtered_data[0:4]\n\n    rho = (local_pressure*0.02897)/(8.314472*(local_temp+273.15))\n\n    velocity_pitots = list(map(lambda x: ((2*abs(x)/rho)**0.5), pressures_data)) #se calcula la velocidad de cada pitot con la presion filtrada                              \n\n    #proccessed_pitot_couples = PitotProcess(pressures_data, rho, euler_angles) #TAL VEZ ELIMINAR LOCAL_TEMP\n    wind_velocity_NED = PitotProcess(pressures_data, rho, euler_angles, imu_velocity)\n\n    database_pitots.loc[i] = [velocity_pitots[0], velocity_pitots[1], velocity_pitots[2], velocity_pitots[3], wind_velocity_NED[0], wind_velocity_NED[1], wind_velocity_NED[2]]\n    #print(filtered_data-new_Value)\n\nprint(rho) "

In [76]:
dataset = calcVelocity(dataset, dt=0.01)

c:\Users\olgaj\Desktop\CUBE-SAT-FLIGHT-DYNAMICS-PITOTS\simulacion\functions\calcVelocity.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset['vel_x'] = vel_x
c:\Users\olgaj\Desktop\CUBE-SAT-FLIGHT-DYNAMICS-PITOTS\simulacion\functions\calcVelocity.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset['vel_y'] = vel_y
c:\Users\olgaj\Desktop\CUBE-SAT-FLIGHT-DYNAMICS-PITOTS\simulacion\functions\calcVelocity.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset['vel_z'] = vel_z

In [77]:
dataset

,press_1,press_2,press_3,press_4,temp_1,temp_2,temp_3,temp_4,bme_press,euler_x,euler_y,euler_z,lin_accel_x,lin_accel_y,lin_accel_z,height,vel_x,vel_y,vel_z
0,-41.56,-40.51,77.33,-34.20,21.83,20.85,20.36,20.76,915.96,0.00,0.00,0.00,0.00,0.00,0.00,860.0,0.00000,0.00000,0.00000
1,-43.66,-33.14,77.33,-34.20,21.83,20.85,20.36,20.76,915.93,358.94,12.25,1.56,0.00,0.07,-0.04,870.0,0.00000,0.00035,-0.00020
2,-43.66,-40.51,77.33,-34.20,21.83,20.95,20.36,20.76,915.96,358.94,12.25,1.56,-0.03,0.00,-0.02,880.0,-0.00015,0.00070,-0.00050
3,-38.40,-40.51,78.39,-34.20,21.93,20.95,20.36,20.76,915.94,358.94,12.38,1.56,0.00,-0.06,-0.01,890.0,-0.00030,0.00040,-0.00065
4,-38.40,-42.61,82.59,-34.20,21.93,20.95,20.36,20.76,915.94,358.94,12.44,1.56,-0.04,-0.10,-0.10,900.0,-0.00050,-0.00040,-0.00120
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77,-40.51,-39.46,81.54,-37.35,22.03,21.05,20.56,20.95,915.67,3.44,-13.94,0.25,-0.24,-1.03,-0.10,860.0,0.01320,-0.02235,-0.00760
78,-41.56,-40.51,81.54,-36.30,22.03,21.05,20.56,20.95,915.69,2.88,-16.56,0.88,-0.12,-0.11,-0.03,850.0,0.01140,-0.02805,-0.00825
79,-43.66,-39.46,78.39,-37.35,21.93,21.05,20.56,20.95,915.68,0.81,2.69,-0.25,0.01,0.12,-0.05,840.0,0.01085,-0.02800,-0.00865
80,-43.66,-40.51,82.59,-37.35,22.03,21.05,20.56,20.95,915.68,0.81,-9.31,2.00,0.25,-0.05,0.02,830.0,0.01215,-0.02765,-0.00880
81,-43.66,-39.46,79.44,-37.35,22.03,21.05,20.56,20.95,915.70,1.12,-7.50,2.88,-0.07,-0.71,0.47,820.0,0.01305,-0.03145,-0.00635

In [78]:
for i in range(len(dataset)):
    row = dataset.loc[i]

    # Presiones
    pressures_data = [row['press_1'], row['press_2'], row['press_3'], row['press_4']]

    # Temperaturas
    local_temp = row[['temp_1', 'temp_2', 'temp_3', 'temp_4']].mean()
    local_pressure = row['bme_press']

    rho = (local_pressure * 0.02897) / (8.314472 * (local_temp + 273.15))

    # Euler
    euler_angles = [row['euler_x'], row['euler_y'], row['euler_z']]

    # Velocidad IMU
    imu_velocity = [row['vel_x'], row['vel_y'], row['vel_z']]

    # Procesamiento
    velocity_pitots = list(map(lambda x: ((2 * abs(x) / rho) ** 0.5), pressures_data))
    wind_velocity_NED = PitotProcess(pressures_data, rho, euler_angles, imu_velocity)

    # Save in dataframe
    database_pitots.loc[i] = [
        velocity_pitots[0], velocity_pitots[1], velocity_pitots[2], velocity_pitots[3],
        wind_velocity_NED[0], wind_velocity_NED[1], wind_velocity_NED[2]
    ]

In [79]:
database_pitots #RESULTADO FINAL, VELOCIDAD MEDIDA EN CADA PITOT Y EN LAS DOS PAREJAS, en m/s

,V1,V2,V3,V4,N,E,D
0,87.519558,86.406909,119.382687,79.392668,-31.863129,7.014240,0.000000
1,89.704933,78.153910,119.384642,79.393969,0.564144,-27.938075,-10.078169
2,89.707276,86.410581,119.387761,79.396043,-5.215206,-29.715856,-4.459343
3,84.134596,86.415197,120.209650,79.400284,-5.286939,-36.326141,-1.746718
4,84.134596,88.626739,123.387946,79.400284,-6.866904,-39.701074,1.609804
...,...,...,...,...,...,...,...
77,86.449603,85.321881,122.649910,83.009383,-5.662715,-3.746887,-35.647780
78,87.561846,86.448659,122.648571,81.833373,18.755550,15.644846,25.630200
79,89.743485,85.317791,120.251747,83.005404,27.722970,-5.419834,11.787963
80,89.747297,86.449131,123.436399,83.008929,-15.980799,29.188243,-6.360895
81,89.746317,85.320483,121.058248,83.008023,12.140444,-4.301582,-28.650557